/* Renders every piece of text, link and media from content/site.json.
   Non-coders: edit content/site.json (or use a CMS on top of it). Do not edit this file. */
(function () {
  'use strict';
  var $ = function (s, r) { return (r || document).querySelector(s); };
  var $$ = function (s, r) { return Array.prototype.slice.call((r || document).querySelectorAll(s)); };
  var page = document.body.dataset.page;
  var home = page === 'home';

  function h(tag, attrs) {
    var e = document.createElement(tag);
    attrs = attrs || {};
    Object.keys(attrs).forEach(function (k) {
      var v = attrs[k];
      if (v === false || v == null) return;
      if (k === 'class') e.className = v;
      else if (k === 'text') e.textContent = v;
      else e.setAttribute(k, v === true ? '' : v);
    });
    for (var i = 2; i < arguments.length; i++) {
      var kids = [].concat(arguments[i]);
      kids.forEach(function (k) { if (k != null && k !== false) e.append(k.nodeType ? k : document.createTextNode(k)); });
    }
    return e;
  }
  function get(o, path) { return path.split('.').reduce(function (a, k) { return a == null ? a : a[k]; }, o); }

  var DEFS = '<svg width="0" height="0" style="position:absolute" aria-hidden="true" focusable="false"><defs>' +
    '<clipPath id="m1" clipPathUnits="objectBoundingBox"><path d="M0.5,0.03 C0.8,0 0.99,0.25 0.96,0.52 C0.94,0.8 0.72,0.99 0.44,0.97 C0.16,0.95 0.01,0.72 0.04,0.45 C0.07,0.2 0.24,0.06 0.5,0.03Z"/></clipPath>' +
    '<clipPath id="m2" clipPathUnits="objectBoundingBox"><path d="M0.06,0.94 C0.02,0.5 0.2,0.12 0.62,0.05 C0.82,0.02 0.96,0.04 0.98,0.06 C1,0.5 0.8,0.9 0.42,0.97 C0.24,1 0.1,0.98 0.06,0.94Z"/></clipPath>' +
    '<clipPath id="m3" clipPathUnits="objectBoundingBox"><path d="M0.02,0.98 L0.02,0.5 C0.02,0.2 0.24,0.02 0.5,0.02 C0.76,0.02 0.98,0.2 0.98,0.5 L0.98,0.98Z"/></clipPath>' +
    '<clipPath id="m4" clipPathUnits="objectBoundingBox"><path d="M0.3,0.08 C0.5,-0.02 0.8,0.03 0.9,0.25 C1,0.45 0.98,0.7 0.82,0.88 C0.65,1.02 0.35,1 0.18,0.86 C0,0.7 0,0.4 0.1,0.24 C0.15,0.16 0.22,0.11 0.3,0.08Z"/></clipPath>' +
    '</defs></svg>';

  // Generated artwork fills every media slot until a real file loads, so nothing looks empty.
  function art(kind, label) {
    var NS = 'http://www.w3.org/2000/svg', s = document.createElementNS(NS, 'svg'), i, j;
    s.setAttribute('viewBox', '0 0 100 100'); s.setAttribute('preserveAspectRatio', 'xMidYMid slice'); s.setAttribute('aria-hidden', 'true');
    function add(t, a) { var e = document.createElementNS(NS, t); for (var k in a) e.setAttribute(k, a[k]); s.appendChild(e); return e; }
    add('rect', { width: 100, height: 100, fill: 'var(--paper)' });
    if (kind === 'grid') {
      for (i = 0; i < 8; i++) for (j = 0; j < 8; j++)
        add('circle', { cx: 10.5 + i * 11.2, cy: 10.5 + j * 11.2, r: (1.4 + (Math.sin(i * .9) + Math.cos(j * .7) + 2) / 4 * 4.6).toFixed(2), fill: (i + j) % 5 === 0 ? 'var(--tomato)' : 'var(--leaf)' });
    } else if (kind === 'pulse') {
      for (i = 0; i < 7; i++) {
        var d = 'M0,' + (14 + i * 12).toFixed(1);
        for (var x = 0; x <= 100; x += 4) d += ' L' + x + ',' + (14 + i * 12 + Math.sin(x * .22 + i * .8) * (3 + (i % 3) * 1.6)).toFixed(1);
        add('path', { d: d, fill: 'none', stroke: i === 3 ? 'var(--tomato)' : 'var(--leaf)', 'stroke-width': i === 3 ? 2.4 : 1.3, 'stroke-linecap': 'round' });
      }
    } else if (kind === 'orbit') {
      add('circle', { cx: 38, cy: 50, r: 30, fill: 'var(--leaf)', style: 'mix-blend-mode:var(--blend)' });
      add('circle', { cx: 62, cy: 50, r: 30, fill: 'var(--tomato)', style: 'mix-blend-mode:var(--blend)' });
      add('circle', { cx: 50, cy: 50, r: 44, fill: 'none', stroke: 'var(--leaf)', 'stroke-width': .6, 'stroke-dasharray': '1 3' });
    } else if (kind === 'initials') {
      add('rect', { width: 100, height: 100, fill: 'var(--leaf)', 'fill-opacity': .14 });
      add('text', { x: 50, y: 62, 'text-anchor': 'middle', fill: 'var(--leaf)', 'font-size': 34, 'font-family': 'Young Serif,Georgia,serif' }).textContent =
        String(label || '').replace(/[.,]/g, '').split(/\s+/).filter(function (w) { return /^[A-Za-z]/.test(w) && !/^(Ph|DBA|Dr)$/i.test(w); }).map(function (w) { return w[0]; }).slice(0, 2).join('').toUpperCase();
    } else {
      add('text', { x: 50, y: 54, 'text-anchor': 'middle', fill: 'var(--ink)', 'font-size': Math.min(13, 118 / Math.max(6, String(label).length)).toFixed(1), 'font-family': 'Young Serif,Georgia,serif' }).textContent = label;
    }
    return h('div', { class: 'ph' }, s);
  }
  // media: file/URL in the slot replaces the artwork once it loads. Videos autoplay muted.
  function media(src, label, cls, kind) {
    var wrap = h('div', { class: 'slot ' + (cls || '') });
    var ph = art(kind, label);
    wrap.append(ph);
    if (!src) return wrap;
    var vid = /\.(mp4|webm|mov)$/i.test(src);
    var el = vid ? document.createElement('video') : h('img', { alt: label || '', loading: 'lazy' });
    if (vid) { el.muted = true; el.loop = true; el.autoplay = true; el.playsInline = true; el.preload = 'metadata'; el.setAttribute('muted', ''); }
    el.addEventListener(vid ? 'loadeddata' : 'load', function () { ph.remove(); });
    el.addEventListener('error', function () { el.remove(); });
    el.src = src;
    wrap.prepend(el);
    return wrap;
  }
  var MASKS = ['mk1', 'mk2', 'mk3', 'mk4'];

  function renderChrome(D) {
    var nav = D.nav.map(function (n) { return h('a', { href: n.href || (home ? n.anchor : n.page) }, n.label); });
    nav.push(h('a', { class: 'nav-cta', href: home ? '#contact' : 'index.html#contact' }, 'Contact'));
    var brand = h('a', { class: 'brand', href: home ? '#top' : 'index.html', 'aria-label': D.site.name + ', home' });
    brand.innerHTML = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 13V3h18v18h-8" fill="none" stroke="currentColor" stroke-width="2.6" stroke-linejoin="miter"/><path d="M3 19h6" fill="none" stroke="var(--tomato)" stroke-width="2.6"/></svg>';
    brand.append(D.site.name);
    $('#site-header').append(h('div', { class: 'bar' }, brand, h('nav', { 'aria-label': 'Primary' }, nav)));
    var c = D.contact;
    $('#site-footer').append(h('div', { class: 'cols' },
      h('div', {}, h('p', { class: 'fname', text: D.site.name }), h('p', {}, 'Inquiries and press: ', h('a', { href: 'mailto:' + c.press }, c.press)), h('p', {}, 'Deals: ', h('a', { href: 'mailto:' + c.deals }, c.deals))),
      h('div', {}, h('p', {}, h('a', { href: c.linkedin }, 'LinkedIn')), h('p', {}, h('a', { href: c.privacy }, 'Privacy policy')), h('p', {}, h('a', { href: c.terms }, 'Terms of use')))));
  }

  function renderThemes(D) {
    var m = $('#themes'); if (!m) return;
    D.themes.forEach(function (t, i) {
      m.append(h('section', { class: 'scene', 'data-bg': t.bg, 'data-fg': t.fg },
        h('div', {}, h('h2', { text: t.title }), h('p', { text: t.text })),
        h('div', { class: 'scene-media' }, media(t.media, t.title, MASKS[(i + 1) % 4], t.art || 'orbit'))));
    });
  }

  function renderStats(D) {
    var m = $('#stats'); if (!m) return;
    D.stats.forEach(function (s) {
      var dec = (String(s.number).split('.')[1] || '').length;
      var b = h('b', { text: (s.prefix || '') + s.number + (s.suffix || ''), 'data-count': s.number, 'data-dec': dec, 'data-prefix': s.prefix || '', 'data-suffix': s.suffix || '' });
      m.append(h('div', { class: 'stat' }, b, h('span', { text: s.label })));
    });
  }

  function renderNet(D) {
    var svg = $('#net'); if (!svg) return;
    var NS = 'http://www.w3.org/2000/svg', cx = 500, cy = 380, cap = $('#net-cap'), idle = '', n = 0;
    function el(t, a, p) { var e = document.createElementNS(NS, t); for (var k in a) e.setAttribute(k, a[k]); (p || svg).appendChild(e); return e; }
    function ring(list, rx, ry, start, step, cls) {
      list.forEach(function (d, i) {
        var ang = (start + i * step) * Math.PI / 180, x = cx + rx * Math.cos(ang), y = cy + ry * Math.sin(ang);
        el('line', { x1: cx, y1: cy, x2: x, y2: y, class: 'edge' });
        var g = el('a', { href: d.url, class: 'node ' + cls, 'aria-label': d.name, tabindex: 0 });
        var w = d.short.length * 11.2 + 34;
        el('rect', { x: x - w / 2, y: y - 21, width: w, height: 42, rx: 21 }, g);
        el('text', { x: x, y: y + 6.5, 'text-anchor': 'middle' }, g).textContent = d.short;
        g.addEventListener('mouseenter', function () { cap.textContent = d.name; });
        g.addEventListener('focus', function () { cap.textContent = d.name; });
        g.addEventListener('mouseleave', function () { cap.textContent = idle; });
      });
    }
    ring(D.ecosystem.partners, 360, 300, -90, 360 / D.ecosystem.partners.length, 'p');
    ring(D.ecosystem.anchors, 170, 130, -90, 120, 'a');
    var hub = el('g', { class: 'hub' }); el('circle', { cx: cx, cy: cy, r: 66 }, hub);
    el('text', { x: cx, y: cy + 10, 'text-anchor': 'middle' }, hub).textContent = 'TMG';
    cap.textContent = idle;
  }

  function renderPortfolio(D) {
    var t = $('#track'), l = $('#pfgrid');
    D.portfolio.forEach(function (p, i) {
      var card = function () { return h('a', { class: 'card', href: p.url }, media(p.media, p.name, MASKS[i % 4] + ' logo', 'wordmark'), h('h3', { text: p.name }), p.note ? h('small', { text: p.note }) : null); };
      if (t) t.append(card());
      if (l) l.append(card());
    });
  }

  function renderPeople(D) {
    var g = $('#people-grid'); if (!g) return;
    var dlg = null;
    if (home) {
      dlg = h('dialog', { id: 'bio' }, h('h3'), h('small'), h('p'), h('button', { class: 'btn', type: 'button' }, 'Close'));
      document.body.append(dlg);
      $('button', dlg).addEventListener('click', function () { dlg.close(); });
      dlg.addEventListener('click', function (e) { if (e.target === dlg) dlg.close(); });
    }
    D.people.forEach(function (p, i) {
      var inner = [media(p.photo, p.name, MASKS[i % 4], 'initials'), h('h3', { text: p.name }), p.role ? h('small', { text: p.role }) : null];
      if (home) {
        var b = h('button', { class: 'person', type: 'button' }, inner);
        b.addEventListener('click', function () {
          $('h3', dlg).textContent = p.name; $('small', dlg).textContent = p.role || '';
          $('p', dlg).textContent = p.bio || 'Full profile coming soon.';
          dlg.showModal();
        });
        g.append(b);
      } else {
        g.append(h('div', { class: 'person' }, inner, p.bio ? h('p', { text: p.bio }) : null));
      }
    });
  }

  function renderNews(D) {
    var m = $('#news'); if (!m) return;
    D.news.forEach(function (n) {
      m.append(h('a', { href: n.url }, h('small', { text: n.date + (n.tag ? ', ' + n.tag : '') }), h('strong', { text: n.title })));
    });
  }

  function renderPartnersList(D) {
    var m = $('#partners-list'); if (!m) return;
    D.ecosystem.anchors.concat(D.ecosystem.partners).forEach(function (p) { m.append(h('li', {}, h('a', { href: p.url }, p.name))); });
  }

  function renderForm(D) {
    var f = $('#signup'); if (!f) return;
    [['first', 'First name', 'given-name'], ['last', 'Last name', 'family-name'], ['company', 'Company name', 'organization'], ['email', 'Email', 'email']].forEach(function (x) {
      f.append(h('div', {}, h('label', { for: 'f-' + x[0], text: x[1] }), h('input', { id: 'f-' + x[0], name: x[0], required: true, autocomplete: x[2], type: x[0] === 'email' ? 'email' : 'text' })));
    });
    var ok = h('p', { class: 'ok', role: 'status' });
    f.append(h('button', { class: 'btn', type: 'submit' }, 'Subscribe'), ok);
    if (D.site.formAction) { f.setAttribute('action', D.site.formAction); f.setAttribute('method', 'post'); }
    else f.addEventListener('submit', function (e) { e.preventDefault(); ok.textContent = 'Thanks, ' + $('#f-first').value + '. You are on the list.'; f.reset(); });
  }

  function apply(D) {
    document.body.insertAdjacentHTML('afterbegin', DEFS);
    $$('[data-text]').forEach(function (e) { var v = get(D, e.dataset.text); if (v != null) e.textContent = v; });
    renderChrome(D); renderThemes(D); renderStats(D); renderNet(D); renderPortfolio(D);
    renderPeople(D); renderNews(D); renderPartnersList(D); renderForm(D);
    window.TMG_READY = true;
    document.dispatchEvent(new Event('tmg:ready'));
  }

  if (window.TMG_DATA) apply(window.TMG_DATA);
  else fetch('site.json').then(function (r) { return r.json(); }).then(apply)
    .catch(function (e) { document.body.insertAdjacentHTML('afterbegin', '<p style="padding:90px 24px">Could not load site.json. Serve the folder over http (see README) instead of opening the file directly.</p>'); console.error(e); });
})();
